### PR TITLE
fix bug #2361

### PR DESCRIPTION
**Pull request by zhujunling-nj**
Chinese name of test case can not display correct on console log

### CODE REVIEW

**Comment by HelioGuilherme66** [comment]
@zhujunling-nj Please consider conditioning your change only to WINDOWS operating system.
Output is correct on my Fedora 36, with Python 3.10 and wxPython 4.0.7 (or 4.2.0).
image
 
 ```
20221009 12:11:13.688 [INFO]: Found Robot Framework version 5.1b2 from /home/helio/.local/lib/python3.10/site-packages/robot.
20221009 12:11:13.689 [INFO]: Started RIDE v2.0rc1.dev1 using python version 3.10.7 with wx version 4.0.7 in linux.
```

This is the test case I used:
```
測試案例 3
    [Tags]    china
    No Operation
    Log To Console    This is Chinese 測試案例
    Log Variables
    Log Many
    Comment    I am going to write a big line of text just to see how it behaves, let's add more text to see how it adjusts
    Comment    Log    Another line added and changed empty teste changed on Text another change
```

**Comment by zhujunling-nj** [comment]
Run with python 3.10.7 and wxPython 4.2.0 on Windows 10.

**Comment by zhujunling-nj** [comment]
The biggest problem is that the encoding of the CONSOLE output under Windows is OEMCP.
When using my commit, the output is normal.
image

**Review by HelioGuilherme66 — APPROVED** [review]
@zhujunling-nj Excellent fix. thanks!

**Pull request merged**
