### PR TITLE
Changes log tab name to 'RIDE Log' and other minor improvements.

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
Better .format arguments.
Adds wx2.9 without announcing it.
Improves print and text with format().

### CODE REVIEW

**Comment by yanne** [comment]
@HelioGuilherme66 have you actually tried to run RIDE with wxPython2.9? At some point, it had many incompatible APIs (even more that 3.0). I cannot really test it myself. From my point of view, it would be enough to just support 3.0 and skip 2.9 altogether.

**Comment by pekkaklarck** [comment]
Definitely no need to support wxPython 2.9. It was a developement series.

**Comment by HelioGuilherme66** [comment]
@yanne Yes I did see some errors in output. (I have some trouble with 2.8.12.1, there are no packages for Fedora, and local build fails with segmentation fault. So I am unable to test in 2.8.12.1) 
@pekkaklarck I did not know of that.
I will revert that change, and only test in 3.0.

**Comment by yanne** [comment]
I merged this on the command line to be able to resolve some conflicts. I'll close this.

**Pull request merged**
