### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by rivercory**
I added Korean translations for the convenience of Korean users!
Please review my PR and give me feedback!

### CODE REVIEW

**Comment by HelioGuilherme66** [comment]
@rivercory Thank you for the Pull Request.
I would be happy to add Korean to RIDE, but it would be "a bit" against the original purpose to have RIDE in the same languages supported by Robot Framework. If your PR would contain an high percentage of translations done, I could consider adding this to RIDE. Maybe you could use automated translation (Machine Translation) with some tool like `poEdit` to increase this translation, and then I would reconsider. You may see at the Crowdin project many languages without translation, and others with MT, but not approved by real users. Adding Korean, could be another language to that group.

What to do next?
I suggest for you to add the Korean translation to Robot Framework, it is a very small set of phrases/words (37 in total) when compared with RIDE.
You can see this [file](https://github.com/robotframework/robotframework/blob/master/src/robot/conf/languages.py) at https://github.com/robotframework/ .
Then you can also be the translator at [Crowdin - Robot Framework](https://robotframework.crowdin.com/robot-framework) and [Crowdin - RIDE](https://crowdin.com/project/robotframework-ride).
(I see that there are some languages translated in Crowdin, but not added to project file. This makes easier to add Korean.)

If you want to talk more about this, please use our #ride channel in Slack.

**Comment by HelioGuilherme66** [comment]
@rivercory I saw you PR at robotframework, and there is a big list of pending PR there. I decided to integrate robotframework's languages.py file in RIDE code. This means that I have integrated your PR in my PR #2851, essentially the localization structure. With this PR, I have setup Korean to be translated at [Crowdin](https://crowdin.com/project/robotframework-ride/ko) (which I hope you can be a translator, and advertise to your colleagues and friends).

Now, one thing I would like to advise to you, is the way "we" expect the PR to be created. I say we, because in general, and in particular in GitHub RobotFramework projects, PR should be created from a topic branch (a dedicated branch to the changes). Please see the [CONTRIBUTING](https://github.com/robotframework/RIDE/blob/master/CONTRIBUTING.adoc#pull-requests) document (and also the one at core RobotFramework).

Thanks.

**Comment by rivercory** [comment]
@HelioGuilherme66
I appreciate it!
If so, should I only add translations to crowdin?
Also, will my PR of robotframework be merged?

**Comment by HelioGuilherme66** [comment]
>If so, should I only add translations to crowdin?
Yes, that is the usual process. But if you use an external tool like, `poedit` the RIDE.po file can be uploaded.

>Also, will my PR of robotframework be merged?
I don't control that, and the owner is temporarily away, so it may take some time. I am sure it will be merged.

**Comment by HelioGuilherme66** [comment]
Yes, you can close, because it came from `master` and it is difficult to manage conflicts.

**Pull request closed without merging**
